### ISSUE TITLE
Spotted

### ISSUE THREAD

**Issue by matteobruni** [F0rty-Tw0/portfolio#1]
Hi @F0rty-Tw0,

I found this comment searching through GitHub:

https://github.com/F0rty-Tw0/portfolio/blob/ab84c50eff5fb0a94e625df0dd4ebd9b1d1f0024/pages/index.js#L7

`react-particles-js` and `react-tsparticles` are almost the same library, the second one is maintained by me, the other uses `tsParticles` core but is not updated with it.

The main difference is about default values, `react-particles-js` have its own, `react-tsparticles` uses the main library defaults.

So a small config with these two libraries can have different behaviour. If you want to try just replace the dependency and the `import`/`require`, everything should work fine.

**Comment by F0rty-Tw0** [comment]
Thank you very much, I'll look later into it when will start editing.
